import type {
  UserProfile,
  Subscription,
  Subject,
  QuizSession,
  Badge,
  AISession,
  ExamCountdown,
  WeeklyScoreData,
  XPProgressData,
  AIMessage,
} from '@/types';

export const mockUser: UserProfile = {
  id: 'student-001',
  email: 'aminata.diallo@gmail.com',
  fullName: 'Aminata Diallo',
  role: 'student',
  examSeries: 'bac_d',
  language: 'fr',
  xpTotal: 4280,
  level: 12,
  streakDays: 7,
  lastStudyDate: '2026-06-18',
  createdAt: '2026-03-01',
};

export const mockSubscription: Subscription = {
  id: 'sub-001',
  userId: 'student-001',
  tier: 'pass_chrono',
  status: 'expiring',
  startDate: '2026-06-11',
  endDate: '2026-06-19',
  priceFcfa: 500,
  aiSessionsUsed: 18,
  aiSessionsLimit: null,
};

export const mockSubjects: Subject[] = [
  {
    id: 'subj-math',
    name: 'Mathématiques',
    nameEn: 'Mathematics',
    category: 'sciences',
    icon: '∑',
    color: '#7C3AED',
    progressPercent: 72,
    lastScore: 14.5,
    sessionsCount: 23,
  },
  {
    id: 'subj-physique',
    name: 'Physique-Chimie',
    nameEn: 'Physics-Chemistry',
    category: 'sciences',
    icon: '⚗',
    color: '#3B82F6',
    progressPercent: 58,
    lastScore: 12.0,
    sessionsCount: 17,
  },
  {
    id: 'subj-svt',
    name: 'Sciences de la Vie',
    nameEn: 'Life Sciences',
    category: 'sciences',
    icon: '🧬',
    color: '#10B981',
    progressPercent: 81,
    lastScore: 16.0,
    sessionsCount: 19,
  },
  {
    id: 'subj-histoire',
    name: 'Histoire-Géographie',
    nameEn: 'History-Geography',
    category: 'histoire',
    icon: '🌍',
    color: '#F59E0B',
    progressPercent: 44,
    lastScore: 10.5,
    sessionsCount: 11,
  },
  {
    id: 'subj-francais',
    name: 'Français',
    nameEn: 'French',
    category: 'langues',
    icon: 'A',
    color: '#EC4899',
    progressPercent: 65,
    lastScore: 13.0,
    sessionsCount: 14,
  },
  {
    id: 'subj-philo',
    name: 'Philosophie',
    nameEn: 'Philosophy',
    category: 'litterature',
    icon: '💭',
    color: '#8B5CF6',
    progressPercent: 35,
    lastScore: 9.5,
    sessionsCount: 8,
  },
];

export const mockBadges: Badge[] = [
  {
    id: 'badge-streak-7',
    name: 'Série de Feu',
    nameEn: 'Fire Streak',
    description: '7 jours consécutifs d\'étude',
    icon: '🔥',
    color: '#F59E0B',
    earnedAt: '2026-06-18',
    category: 'streak',
  },
  {
    id: 'badge-math-ace',
    name: 'As des Maths',
    nameEn: 'Math Ace',
    description: 'Score > 15/20 en Mathématiques',
    icon: '🏆',
    color: '#7C3AED',
    earnedAt: '2026-06-15',
    category: 'score',
  },
  {
    id: 'badge-svt-master',
    name: 'Biologiste',
    nameEn: 'Biologist',
    description: '80% de progression en SVT',
    icon: '🧬',
    color: '#10B981',
    earnedAt: '2026-06-12',
    category: 'completion',
  },
  {
    id: 'badge-first-exam',
    name: 'Premier Examen',
    nameEn: 'First Exam',
    description: 'Premier examen blanc complété',
    icon: '📋',
    color: '#3B82F6',
    earnedAt: '2026-06-08',
    category: 'completion',
  },
  {
    id: 'badge-curious',
    name: 'Curieux',
    nameEn: 'Curious Mind',
    description: '50 questions posées à l\'IA',
    icon: '🔍',
    color: '#EC4899',
    earnedAt: '2026-06-05',
    category: 'engagement',
  },
];

export const mockAISessions: AISession[] = [
  {
    id: 'ai-session-001',
    subjectId: 'subj-math',
    subjectName: 'Mathématiques',
    subjectIcon: '∑',
    startedAt: '2026-06-18T08:30:00',
    duration: 42,
    messagesCount: 14,
    xpEarned: 85,
    summary: 'Dérivées et primitives — fonctions composées',
  },
  {
    id: 'ai-session-002',
    subjectId: 'subj-svt',
    subjectName: 'Sciences de la Vie',
    subjectIcon: '🧬',
    startedAt: '2026-06-17T19:15:00',
    duration: 28,
    messagesCount: 9,
    xpEarned: 60,
    summary: 'Cycle cellulaire et mitose',
  },
  {
    id: 'ai-session-003',
    subjectId: 'subj-physique',
    subjectName: 'Physique-Chimie',
    subjectIcon: '⚗',
    startedAt: '2026-06-17T14:00:00',
    duration: 35,
    messagesCount: 11,
    xpEarned: 70,
    summary: 'Circuits RC — charge et décharge',
  },
  {
    id: 'ai-session-004',
    subjectId: 'subj-histoire',
    subjectName: 'Histoire-Géographie',
    subjectIcon: '🌍',
    startedAt: '2026-06-16T20:00:00',
    duration: 20,
    messagesCount: 7,
    xpEarned: 45,
    summary: 'Décolonisation en Afrique subsaharienne',
  },
];

export const mockQuizSessions: QuizSession[] = [
  {
    id: 'quiz-001',
    userId: 'student-001',
    subjectId: 'subj-math',
    subjectName: 'Mathématiques',
    score: 14.5,
    totalQuestions: 20,
    duration: 25,
    completedAt: '2026-06-18',
    xpEarned: 72,
  },
  {
    id: 'quiz-002',
    userId: 'student-001',
    subjectId: 'subj-svt',
    subjectName: 'Sciences de la Vie',
    score: 16.0,
    totalQuestions: 15,
    duration: 18,
    completedAt: '2026-06-17',
    xpEarned: 80,
  },
  {
    id: 'quiz-003',
    userId: 'student-001',
    subjectId: 'subj-physique',
    subjectName: 'Physique-Chimie',
    score: 12.0,
    totalQuestions: 20,
    duration: 30,
    completedAt: '2026-06-16',
    xpEarned: 60,
  },
];

export const mockExamCountdown: ExamCountdown = {
  examName: 'Baccalauréat Série D',
  examSeries: 'Bac D',
  targetDate: '2026-07-15',
  daysRemaining: 27,
  hoursRemaining: 648,
};

export const mockWeeklyScores: WeeklyScoreData[] = [
  { week: 'S1 Mai', math: 9.5, physique: 8.0, svt: 11.0, histoire: 7.5 },
  { week: 'S2 Mai', math: 10.5, physique: 9.5, svt: 12.5, histoire: 8.0 },
  { week: 'S3 Mai', math: 11.0, physique: 10.0, svt: 13.0, histoire: 8.5 },
  { week: 'S4 Mai', math: 12.5, physique: 11.5, svt: 14.0, histoire: 9.0 },
  { week: 'S1 Jun', math: 13.0, physique: 10.5, svt: 15.0, histoire: 9.5 },
  { week: 'S2 Jun', math: 13.5, physique: 12.0, svt: 15.5, histoire: 10.0 },
  { week: 'S3 Jun', math: 14.5, physique: 12.0, svt: 16.0, histoire: 10.5 },
];

export const mockXPProgress: XPProgressData[] = [
  { date: '01 Jun', xp: 120, cumulative: 2800 },
  { date: '03 Jun', xp: 85, cumulative: 2885 },
  { date: '05 Jun', xp: 145, cumulative: 3030 },
  { date: '07 Jun', xp: 60, cumulative: 3090 },
  { date: '09 Jun', xp: 190, cumulative: 3280 },
  { date: '11 Jun', xp: 75, cumulative: 3355 },
  { date: '13 Jun', xp: 220, cumulative: 3575 },
  { date: '15 Jun', xp: 165, cumulative: 3740 },
  { date: '17 Jun', xp: 85, cumulative: 3825 },
  { date: '18 Jun', xp: 455, cumulative: 4280 },
];

export const mockChatMessages: AIMessage[] = [
  {
    id: 'msg-001',
    role: 'user',
    content: 'Bonjour ! J\'ai du mal à comprendre la dérivée d\'une fonction composée. Peux-tu m\'aider ?',
    timestamp: '08:31',
    subjectContext: 'Mathématiques',
  },
  {
    id: 'msg-002',
    role: 'assistant',
    content: 'Bonjour Aminata ! Bien sûr, je suis là pour t\'accompagner 😊\n\nAvant de t\'expliquer la règle, dis-moi : est-ce que tu sais déjà ce qu\'est une **fonction composée** ? Par exemple, si j\'écris f(g(x)), est-ce que tu peux me dire ce que ça signifie dans tes propres mots ?',
    timestamp: '08:31',
    subjectContext: 'Mathématiques',
    xpAwarded: 5,
  },
  {
    id: 'msg-003',
    role: 'user',
    content: 'Je pense que c\'est une fonction dans une autre fonction ? Comme si g(x) = 2x+1 et f(x) = x², alors f(g(x)) = (2x+1)² ?',
    timestamp: '08:33',
  },
  {
    id: 'msg-004',
    role: 'assistant',
    content: 'Excellent ! Tu as parfaitement compris ! 🎉 C\'est exactement ça.\n\nMaintenant, réfléchissons ensemble à la dérivée. Si tu devais dériver f(x) = x², quelle serait la réponse ?',
    timestamp: '08:33',
    xpAwarded: 10,
  },
  {
    id: 'msg-005',
    role: 'user',
    content: "f'(x) = 2x, c'est ça ?",
    timestamp: '08:34',
  },
  {
    id: 'msg-006',
    role: 'assistant',
    content: 'Parfait ! Et si maintenant x est remplacé par g(x) = 2x+1 ?\n\nEssaie d\'appliquer la même règle, mais cette fois en pensant à ce qui change à l\'intérieur. Qu\'obtiens-tu ?',
    timestamp: '08:34',
    xpAwarded: 5,
  },
  {
    id: 'msg-007',
    role: 'user',
    content: "Hmm... 2(2x+1) ? Mais je ne suis pas sûre de ce qu'il faut faire avec le g(x) à l'intérieur.",
    timestamp: '08:36',
  },
  {
    id: 'msg-008',
    role: 'assistant',
    content: 'Tu es très proche ! Tu as bien dérivé la partie extérieure. 👏\n\nIl manque une étape : quand on dérive une fonction composée, on applique la **règle de la chaîne** :\n\n> (f ∘ g)\'(x) = f\'(g(x)) × **g\'(x)**\n\nTu as trouvé f\'(g(x)) = 2(2x+1). Maintenant, quelle est la dérivée de g(x) = 2x+1 ?',
    timestamp: '08:36',
    xpAwarded: 15,
  },
  {
    id: 'msg-009',
    role: 'user',
    content: "g'(x) = 2 ! Donc la réponse finale est 2(2x+1) × 2 = 4(2x+1) = 8x+4 ?",
    timestamp: '08:38',
  },
  {
    id: 'msg-010',
    role: 'assistant',
    content: 'BRAVO ! 🏆 C\'est exactement la bonne réponse !\n\nTu viens d\'appliquer la règle de la chaîne avec succès :\n- f\'(g(x)) = 2(2x+1)\n- g\'(x) = 2\n- **Résultat : 4(2x+1) = 8x+4** ✅\n\nTu as gagné **+15 XP** pour cette session ! 🌟\n\nVeux-tu essayer un autre exemple pour consolider, ou passer à une application avec une fonction trigonométrique ?',
    timestamp: '08:39',
    xpAwarded: 20,
  },
];

export const subscriptionPlans = [
  {
    id: 'plan-free',
    name: 'Gratuit',
    nameEn: 'Free',
    priceFcfa: 0,
    period: null,
    features: ['3 diagnostics IA / semaine', 'Quiz standards', 'Tableau de bord basique'],
    featuresEn: ['3 AI diagnostics / week', 'Standard quizzes', 'Basic dashboard'],
    tier: 'free' as const,
    highlighted: false,
  },
  {
    id: 'plan-chrono',
    name: 'Pass Chrono',
    nameEn: 'Chrono Pass',
    priceFcfa: 500,
    period: 'semaine',
    periodEn: 'week',
    features: ['IA illimitée 7 jours', 'Quiz personnalisés', 'Statistiques avancées'],
    featuresEn: ['Unlimited AI for 7 days', 'Personalized quizzes', 'Advanced stats'],
    tier: 'pass_chrono' as const,
    highlighted: false,
  },
  {
    id: 'plan-premium',
    name: 'Mensuel Premium',
    nameEn: 'Monthly Premium',
    priceFcfa: 1500,
    period: 'mois',
    periodEn: 'month',
    features: ['IA illimitée', 'Examens blancs', 'Suivi avancé', 'Espace parent'],
    featuresEn: ['Unlimited AI', 'Mock exams', 'Advanced tracking', 'Parent space'],
    tier: 'premium' as const,
    highlighted: true,
  },
  {
    id: 'plan-examen',
    name: 'Pass Examen',
    nameEn: 'Exam Pass',
    priceFcfa: 5000,
    period: 'accès unique',
    periodEn: 'one-time',
    features: ['Accès intensif période examen', 'Tout Premium inclus', 'Support prioritaire'],
    featuresEn: ['Intensive exam period access', 'All Premium included', 'Priority support'],
    tier: 'pass_examen' as const,
    highlighted: false,
  },
];

export const examSeriesOptions = [
  { value: 'bac_a', label: 'Bac Série A (Littéraire)', labelEn: 'Bac Series A (Literary)' },
  { value: 'bac_c', label: 'Bac Série C (Mathématiques)', labelEn: 'Bac Series C (Mathematics)' },
  { value: 'bac_d', label: 'Bac Série D (Sciences)', labelEn: 'Bac Series D (Sciences)' },
  { value: 'bac_ti', label: 'Bac Série TI (Technique)', labelEn: 'Bac Series TI (Technical)' },
  { value: 'gce_arts', label: 'GCE A-Level Arts', labelEn: 'GCE A-Level Arts' },
  { value: 'gce_sciences', label: 'GCE A-Level Sciences', labelEn: 'GCE A-Level Sciences' },
];